In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import tensorflow as tf

In [2]:
df=pd.read_csv('Task 3 and 4_Loan_Data.csv')

In [3]:
df.describe()

customer_id  credit_lines_outstanding  loan_amt_outstanding  \
count  1.000000e+04              10000.000000          10000.000000   
mean   4.974577e+06                  1.461200           4159.677034   
std    2.293890e+06                  1.743846           1421.399078   
min    1.000324e+06                  0.000000             46.783973   
25%    2.977661e+06                  0.000000           3154.235371   
50%    4.989502e+06                  1.000000           4052.377228   
75%    6.967210e+06                  2.000000           5052.898103   
max    8.999789e+06                  5.000000          10750.677810   

       total_debt_outstanding         income  years_employed    fico_score  \
count            10000.000000   10000.000000    10000.000000  10000.000000   
mean              8718.916797   70039.901401        4.552800    637.557700   
std               6627.164762   20072.214143        1.566862     60.657906   
min                 31.652732    1000.000000        0.000000    408.000000   
25%               4199.836020   56539.867903        3.000000    597.000000   
50%               6732.407217   70085.826330        5.000000    638.000000   
75%              11272.263740   83429.166133        6.000000    679.000000   
max              43688.784100  148412.180500       10.000000    850.000000   

            default  
count  10000.000000  
mean       0.185100  
std        0.388398  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%        0.000000  
max        1.000000

In [4]:
df

customer_id  credit_lines_outstanding  loan_amt_outstanding  \
0         8153374                         0           5221.545193   
1         7442532                         5           1958.928726   
2         2256073                         0           3363.009259   
3         4885975                         0           4766.648001   
4         4700614                         1           1345.827718   
...           ...                       ...                   ...   
9995      3972488                         0           3033.647103   
9996      6184073                         1           4146.239304   
9997      6694516                         2           3088.223727   
9998      3942961                         0           3288.901666   
9999      5533570                         1           1917.652480   

      total_debt_outstanding       income  years_employed  fico_score  default  
0                3915.471226  78039.38546               5         605        0  
1                8228.752520  26648.43525               2         572        1  
2                2027.830850  65866.71246               4         602        0  
3                2501.730397  74356.88347               5         612        0  
4                1768.826187  23448.32631               6         631        0  
...                      ...          ...             ...         ...      ...  
9995             2553.733144  42691.62787               5         697        0  
9996             5458.163525  79969.50521               8         615        0  
9997             4813.090925  38192.67591               5         596        0  
9998             1043.099660  50929.37206               2         647        0  
9999             3050.248203  30611.62821               6         757        0  

[10000 rows x 8 columns]

In [5]:
dataset=df
X = dataset.iloc[:, 1:6].values
y = dataset.iloc[:, -1].values

In [6]:
print(X)

[[0.00000000e+00 5.22154519e+03 3.91547123e+03 7.80393855e+04
  5.00000000e+00]
 [5.00000000e+00 1.95892873e+03 8.22875252e+03 2.66484352e+04
  2.00000000e+00]
 [0.00000000e+00 3.36300926e+03 2.02783085e+03 6.58667125e+04
  4.00000000e+00]
 ...
 [2.00000000e+00 3.08822373e+03 4.81309093e+03 3.81926759e+04
  5.00000000e+00]
 [0.00000000e+00 3.28890167e+03 1.04309966e+03 5.09293721e+04
  2.00000000e+00]
 [1.00000000e+00 1.91765248e+03 3.05024820e+03 3.06116282e+04
  6.00000000e+00]]


In [7]:
print(y)

[0 1 0 ... 0 0 0]


In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, :] = sc.fit_transform(X_train[:, :])
X_test[:, :] = sc.transform(X_test[:, :])

In [10]:
X_train

array([[ 0.89037767, -0.41530754,  1.33634277,  1.05966068,  0.28594244],
       [-0.26156239,  0.59964786, -0.21539306,  0.92565924,  0.92706899],
       [ 0.89037767, -1.31678738, -0.24057158, -1.31666546,  1.56819554],
       ...,
       [-0.83753242, -1.06756861, -0.53726592, -0.32059366, -0.99631066],
       [-0.83753242, -1.06396376, -0.91314684, -1.09262315,  0.28594244],
       [-0.83753242,  0.08558634, -0.65629996, -0.55268495, -0.35518411]])

#Multiple Linear Regression

In [11]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [13]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0.5  0.  ]
 [0.93 1.  ]
 [0.1  0.  ]
 ...
 [0.07 0.  ]
 [0.08 0.  ]
 [0.02 0.  ]]


In [14]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.7961308859517022

In [15]:
#SVR MODEL
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train, y_train)

SVR()

In [18]:
y_pred = regressor.predict(X_test).reshape(-1,1)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 0.22  0.  ]
 [ 1.03  1.  ]
 [-0.06  0.  ]
 ...
 [ 0.07  0.  ]
 [ 0.02  0.  ]
 [ 0.07  0.  ]]


In [19]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9123597814189313

In [20]:
#decision tree regression
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X_train, y_train)

DecisionTreeRegressor(random_state=0)

In [21]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1. 0.]
 [1. 1.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [22]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.8972719276280731

In [23]:
#random forest regression
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X, y)

RandomForestRegressor(n_estimators=10, random_state=0)

In [24]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.8972719276280731

In [54]:
#logistic regression
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [55]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [56]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1611    3]
 [  13  373]]


0.992

In [28]:
#k-nn
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1609    5]
 [  18  368]]


0.9885

In [44]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

In [43]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1608    6]
 [  13  373]]


0.9905

In [32]:
#decision tree classification
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [33]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1599   15]
 [  14  372]]


0.9855

In [34]:
#random forest classification
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [35]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1607    7]
 [  16  370]]


0.9885

In [36]:
#naive bayes model
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [37]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1565   49]
 [   9  377]]


0.971

In [38]:
#support vector machine
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [39]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1609    5]
 [   9  377]]


0.993

In [40]:
#kernel svm
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

In [41]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1608    6]
 [  13  373]]


0.9905

In [57]:
#model of logistic regression fits the best

In [58]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [59]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [60]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1611    3]
 [  13  373]]


0.992